[build]
# queues
max_queues=256
max_fetch_sqes=1024
worker_queue_size=32768

# dispatcher/workers
coalesce_sqe=1
prefetch_sqe=0
skip_io=0
batch_worker_dma=1
use_cont_qid=0
assign_worker_rr=0
use_committer=0

# timing model
use_agg_timing_update=1
use_cas_timing_update=1

# profiling
profile_req=0

# clean build
clean=1

[load]
num_sched_insts=8
block_size=512
target_latency=50000
target_miops=40
memmap_start=134G
memmap_size=124G
num_service_units=16
num_workers_per_service_unit=1
cpus=44-85
use_disp_dma=1
use_worker_dma=1

# DMA settings
dsa_num_devs=4
dsa_num_grps_per_dev=4
dsa_num_wqs_per_grp=2
dsa_num_engs_per_grp=1
dsa_wq_sizes=2,32
dsa_wq_priorities=1,15
dma_batch_size=16
num_dma_descs_per_worker=32
